paths:
  htmls_dir: data/htmls
  database: data/database.db

downloading:
  sleep_time: 3

modes:
  latest_info:
    switch: False
    save_to_db: False

  save_history_info_to_db:
    switch: False
    date_choice: "2025-03-12" # "YYYY-MM-DD"

  cohere_database:
    switch: False

  gpt_extract_data:
    switch: False


dev:
  debug: True